# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 8453
  start_block: 0
  contracts:
  - name: KickTheMarket
    address:
    - 0x14Dabc24Af69d38701927B68E004c71169790a5d
    - 0x634c4e43Bec566a7704612c8dD1F7c3Dbe28BFDC
    handler: ./src/EventHandlers.js
    events:
    - event: Mint(uint256 indexed tokenId, address indexed to, uint256 score, uint256 anomalyLevel, uint256 blackSwanLevel, uint256 totalKicks, bytes proof)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
  - name: Sponsors
    address:
    - 0x4f17a5529B4E3e20467774708435740792E460eE
    handler: ./src/EventHandlers.js
    events:
    - event: NewSponsor(uint256 indexed week, address indexed sponsor, uint256 indexed amount, uint8 tier, string name, string cta, string description, string logoUrl, string website)
  - name: Jackpot
    address:
    - 0x4DFF47404766cfDf82665A40Eb822870b9A68538
    handler: ./src/EventHandlers.js
    events:
    - event: JackpotWinner(uint64 indexed ticketId, address indexed winner, uint256 prize)
    - event: JackpotClaimed(address indexed winner, uint256 prize, address indexed caller)
    - event: RandomNumberResult(uint64 indexed sequenceNumber, bool isWinner, uint256 randomNumber)
    - event: TicketAssigned(uint64 indexed ticketId, address indexed player, uint256 amount, address indexed gameAddress)
unordered_multichain_mode: true
preload_handlers: true
